/**
 * Accompaniment System Type Definitions
 */

/**
 * Accompaniment instrument type
 */
export type AccompanimentInstrument = 'bass' | 'piano' | 'synth'

/**
 * Accompaniment note pattern
 */
export interface AccompanimentNote {
  time: number          // Time in seconds
  pitch: number         // MIDI note number (0-127)
  velocity: number      // 0-1
  duration?: number     // Note duration in seconds (optional)
}

/**
 * Accompaniment pattern generated by LLM
 */
export interface AccompanimentPattern {
  instrument: AccompanimentInstrument
  theme: string         // Theme description
  duration: number      // Duration in seconds
  bpm?: number          // Beats per minute
  notes: AccompanimentNote[]
  metadata?: {
    generatedBy: string
    prompt: string
    timestamp: string
  }
}

/**
 * Auto-play mode configuration
 */
export interface AutoPlayConfig {
  enabled: boolean
  volume: number        // 0-1
}

